# PROGRAMS
source = ~/hyprdots/hypr/conf/consts.conf

# === MAIN PART ===

# MONITOR
source = ~/hyprdots/hypr/conf/monitor.conf

# Autostart
source = ~/hyprdots/hypr/conf/autostart.conf

# ENV
source = ~/hyprdots/hypr/conf/env.conf

# KEYBOARD
source = ~/hyprdots/hypr/conf/keyboard.conf

# MISC
source = ~/hyprdots/hypr/conf/misc.conf

# BINDS
source = ~/hyprdots/hypr/conf/binds.conf

# === LOOK AND FEEL ===

# ANIMATION
source = ~/hyprdots/hypr/conf/animation.conf

# GENERAL 
source = ~/hyprdots/hypr/conf/general.conf

# DECORATION 
source = ~/hyprdots/hypr/conf/decoration.conf

# WINDOW RULES
source = ~/hyprdots/hypr/conf/windowrules.conf

# LAYOUT
source = ~/hyprdots/hypr/conf/layout.conf
