$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 3, linear
    animation = fadeOut, 1, 3, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    color = rgba(0a0a0aff)
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(121212ff)

    outer_color = rgba(00d1ffee) rgba(00f0ffee) 45deg
    check_color = rgba(50fa7bff) rgba(60eb8aff) 90deg
    fail_color = rgba(ff3838ff) rgba(cc0000ff) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 0

    font_family = $font
    placeholder_text = UNLOCK SYSTEM
    fail_text = $PAMFAIL

    # dots_text_format = *
    dots_size = 0.25
    dots_spacing = 0.25

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 48
    font_family = $font
    color = rgba(e6e6ffff)
    position = 0, -150
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 16
    font_family = $font
    color = rgba(888888ff)
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT[en,ru]
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] sh /home/gagarinten/hyprdots/scripts/hyprdots-00-battery.sh # update every 60 seconds
    font_family = JetBrainsMono Nerd Font
    font_size = 16
    color = rgba(ff3838ff)
    position = -50, 100
    halign = right
    valign = bottom
}
