# hyprsunset - Blue light filter
# https://wiki.hypr.land/Hypr-Ecosystem/hyprsunset/

max-gamma = 100

# Day - neutral temperature
profile {
    time = 6:00
    temperature = 6500
    gamma = 1.0
}

# Evening - warmer
profile {
    time = 20:00
    temperature = 4500
    gamma = 0.9
}

# Night - very warm
profile {
    time = 23:00
    temperature = 3500
    gamma = 0.8
}
