exec-once = hypridle
exec-once = swayosd-server
exec-once = eww daemon
exec-once = eww open topbar
exec-once = swaync
exec-once = hyprpaper
exec-once = elephant

exec-once = systemctl --user start hyprpolkitagent
