exec-once = hypridle
exec-once = swayosd-server
exec-once = swaync
exec-once = hyprpaper

exec-once = walker --gapplication-service
exec-once = elephant

exec-once = systemctl --user start hyprpolkitagent

# EWW
exec-once = eww daemon
exec-once = eww open topbar
exec-once = bash ~/hyprdots/scripts/on_workspace_change.sh
exec-once = bash ~/hyprdots/scripts/detect-hw.sh

