# APPS
$terminal = kitty
$fileManager = nautilus
$menu = walker
$browser = firefox
$screenshot = flameshot gui

# COLOR PALLETE (Tactical Gray)
$base00 = #0a0a0a # fully black
$base01 = #121212 # very dark grey
$base02 = #1a1a1a # dark grey

$alert = #ff3838
$active = #00d1ff
$success = #50fa7b
$font-ui = JetBrainsMono Nerd Font, monospace
