#windowrulev2 = float, class:.*
windowrule = float 1, match:class org.netrs.ui

windowrule = match:class flameshot, no_anim 1
windowrule = match:class flameshot, float 1 
windowrule = match:class flameshot, move 0 0
windowrule = match:class flameshot, pin 1
windowrule = match:class flameshot, no_initial_focus 1
# set this to your leftmost monitor id, otherwise you have to move your cursor to the leftmost monitor
# before executing flameshot
windowrule = match:class flameshot, monitor 1
